md "Todos os Clubes"
cd "Todos os Clubes"
md "Serie A"
md "Serie B"

cd "Serie A"
md "Atlético-MG"
md "Palmeiras"
md "Fortaleza"
md "Bragantino"
md "Flamengo"
md "Athletico-PR"
md "Atlético-GO"
md "Ceará"
md "Internacional"
md "Santos"
md "Corinthians"
md "Juventude"
md "Bahia"
md "São Paulo"
md "Fluminense"
md "Cuiabá"
md "Sport"
md "América-MG"
md "Grêmio"
md "Chapecoense"